### PR TITLE
File field edit dialog

### PR DESCRIPTION
**Pull request by arildm**
Adding Edit button to each file field widget element, which opens an edit form for the referenced file in a modal dialog.

### CODE REVIEW

**Comment by Berdir** [comment]
Talked with Wim Leers, the trick is having a custom controller as I assumed, and then you can call a special method on $form_state. See QuickEditController. We probably don't need to return anything special except maybe the messages or so, just make sure to not redirect.

**Comment by arildm** [comment]
It's not clear to me why a custom controller is necessary.

Also, unrelated AFAIK, the current values of the file are not rendered in the form, although they are present as #default_value in $file_edit_form. I have no clue where to go from here...

**Comment by Berdir** [comment]
Rebased, added a width to make the widget wider. merged.

**Comment by arildm** [comment]
Cool, thanks for the help and sorry about forgetting to remove the WIP tag.

**Pull request merged**
