### PR TITLE
Implement all methods of abstract classes.

### PR DESCRIPTION
**Pull request by queenvictoria**
I found that I could not install the module against Drupal 8.0.x HEAD without some changes. The access methods I've used are definitely wrong.

### CODE REVIEW

**Comment by Berdir** [comment]
Thanks for looking into this. I was working on this as well and forgot to push it. Did not expect anyone to look at file_entity today :) See https://github.com/md-systems/file_entity/commit/a3a90104aeeba84c2d5241008bc66ed54df2cb11 for my fixes.

**Comment by queenvictoria** [comment]
Cool thanks. Looks good except for a typ-oh here
https://github.com/md-systems/file_entity/commit/a3a90104aeeba84c2d5241008bc66ed54df2cb11#diff-5ecaeba1b9c3f219fc6c543382c8052aR649

```
+    ->setLinkTemplate('edit-form', '/file/{file}/edi}')
```

**Comment by Berdir** [comment]
Uups! :)

Want to create a new pull request to fix that?

**Comment by queenvictoria** [comment]
Will do. Thanks!

**Pull request closed without merging**
